apiVersion: apps/v1
kind: Deployment
metadata:
  name: attendance-backend
  labels:
    app: attendance-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attendance-backend
  template:
    metadata:
      labels:
        app: attendance-backend
    spec:
      containers:
        - name: backend
          image: 886682669061.dkr.ecr.eu-north-1.amazonaws.com/ayanchoudhary76/attendance-backend:IMAGE_TAG
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: attendance-secrets
                  key: MONGO_URI
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: attendance-secrets
                  key: JWT_SECRET
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "300m"