apiVersion: v1
kind: Service
metadata:
  name: attendance-backend-svc
spec:
  type: LoadBalancer
  selector:
    app: attendance-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000