apiVersion: v1
kind: Service
metadata:
  name: attendance-frontend-svc
spec:
  type: LoadBalancer
  selector:
    app: attendance-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80