apiVersion: apps/v1
kind: Deployment
metadata:
  name: attendance-frontend
  labels:
    app: attendance-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attendance-frontend
  template:
    metadata:
      labels:
        app: attendance-frontend
    spec:
      containers:
        - name: frontend
          image: 886682669061.dkr.ecr.eu-north-1.amazonaws.com/ayanchoudhary76/attendance-frontend:IMAGE_TAG
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "200m"